/**Generated by core/generateAllConstants
 */

///Common
//table relative z position to 0, measured by end point position
#define TableZ -0.152
#define GripperLength 0.144

///Module specific
#define CALIBRATION_FILE "/src/vision/data/Calibration.ini"
#define CALIBRATION_IMAGE "/src/vision/data/Calibration.jpg"
#define OBJECTS_FILE "/src/vision/data/Objects.ini"
#define DATA_FOLDER "/src/vision/data"

//webcam: "usb_cam/image_raw", kinect:"/camera/rgb/image_raw"
#define IMAGE_TOPIC "/camera/rgb/image_raw"

#define TableBlockY 0.2
#define TableBlockX 0.15
#define BaseToPoint5 0.28
#define BaseX 0.155
#define CameraZ 0.8
