#Generated by core/generateAllConstants

###Common
#table relative z position to 0, measured by end point position
TableZ = -0.152
GripperLength = 0.144

###Module specific
CALIBRATION_FILE = "/src/vision/data/Calibration.ini"
CALIBRATION_IMAGE = "/src/vision/data/Calibration.jpg"
OBJECTS_FILE = "/src/vision/data/Objects.ini"
DATA_FOLDER = "/src/vision/data"

#webcam: "usb_cam/image_raw", kinect:"/camera/rgb/image_raw"
IMAGE_TOPIC = "/camera/rgb/image_raw"

TableBlockY = 0.2
TableBlockX = 0.15
BaseToPoint5 = 0.28
BaseX = 0.155
#to measure
CameraZ = 0.9
