#Generated by core/generateAllConstants

###Common
#table relative z position to 0, measured by end point position
TableZ = -0.152
GripperLength = 0.144

###Module specific
CALIBRATION_FILE = "/src/vision/data/Calibration.ini"
CALIBRATION_IMAGE = "/src/vision/data/Calibration.jpg"
OBJECTS_FILE = "/src/vision/data/Objects.ini"
DATA_FOLDER = "/src/vision/data"

#webcam: "usb_cam/image_raw", kinect:"/camera/rgb/image_raw"
IMAGE_TOPIC = "/camera/rgb/image_raw"

#original table block size
#TableBlockY=0.2
#TableBlockX=0.15
#paper block size
#A3 paper Y=0.42 x=0.297
#block = y/4 ,x/3 
TableBlockY = 0.105
TableBlockX = 0.099
#pull from bolt to point 5
BaseToPoint5 = 0.26
BaseX = 0.155
CameraZ = 0.8
CameraX = 0.287
