#Generated by core/generateAllConstants

###Common
#table relative z position to 0, measured by end point position
TableZ = -0.152
GripperLength = 0.144
poly_dual  =  [(0,-0.36),(0.35,-0.26),(0.55,0),(0.35,0.26),(0,0.36)]
poly_right  =  [(0.1,0.8),(0.3,-0.33),(0.6,-0.5),(0.66,0.22),(0.5,0.7),(0.2,0.88),(0,0.9),(0,0.44),(0.2,0.4),(0.2,0.2)]
poly_left  =  [(0.1,-0.08),(0.2,-0.2),(0.2,-0.4),(0,-0.44),(0,-0.9),(0.2,-0.88),(0.5,-0.7),(0.66,-0.22),(0.6,0.5),(0.3,0.33)]

###Module specific

