/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/robocuphome/robocuphome2015/src/vision/srv/platePosition.srv
 *
 */


#ifndef VISION_MESSAGE_PLATEPOSITIONRESPONSE_H
#define VISION_MESSAGE_PLATEPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct platePositionResponse_
{
  typedef platePositionResponse_<ContainerAllocator> Type;

  platePositionResponse_()
    : p1()
    , p2()
    , p3()
    , p4()  {
      p1.assign(0.0);

      p2.assign(0.0);

      p3.assign(0.0);

      p4.assign(0.0);
  }
  platePositionResponse_(const ContainerAllocator& _alloc)
    : p1()
    , p2()
    , p3()
    , p4()  {
      p1.assign(0.0);

      p2.assign(0.0);

      p3.assign(0.0);

      p4.assign(0.0);
  }



   typedef boost::array<float, 2>  _p1_type;
  _p1_type p1;

   typedef boost::array<float, 2>  _p2_type;
  _p2_type p2;

   typedef boost::array<float, 2>  _p3_type;
  _p3_type p3;

   typedef boost::array<float, 2>  _p4_type;
  _p4_type p4;




  typedef boost::shared_ptr< ::vision::platePositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::platePositionResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct platePositionResponse_

typedef ::vision::platePositionResponse_<std::allocator<void> > platePositionResponse;

typedef boost::shared_ptr< ::vision::platePositionResponse > platePositionResponsePtr;
typedef boost::shared_ptr< ::vision::platePositionResponse const> platePositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::platePositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::platePositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::platePositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::platePositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::platePositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::platePositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::platePositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::platePositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::platePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d86649d6e956fe5ee3b542339248e25";
  }

  static const char* value(const ::vision::platePositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d86649d6e956fe5ULL;
  static const uint64_t static_value2 = 0xee3b542339248e25ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::platePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/platePositionResponse";
  }

  static const char* value(const ::vision::platePositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::platePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[2] p1\n\
float32[2] p2\n\
float32[2] p3\n\
float32[2] p4\n\
\n\
\n\
";
  }

  static const char* value(const ::vision::platePositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::platePositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p1);
      stream.next(m.p2);
      stream.next(m.p3);
      stream.next(m.p4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct platePositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::platePositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::platePositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "p1[]" << std::endl;
    for (size_t i = 0; i < v.p1.size(); ++i)
    {
      s << indent << "  p1[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.p1[i]);
    }
    s << indent << "p2[]" << std::endl;
    for (size_t i = 0; i < v.p2.size(); ++i)
    {
      s << indent << "  p2[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.p2[i]);
    }
    s << indent << "p3[]" << std::endl;
    for (size_t i = 0; i < v.p3.size(); ++i)
    {
      s << indent << "  p3[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.p3[i]);
    }
    s << indent << "p4[]" << std::endl;
    for (size_t i = 0; i < v.p4.size(); ++i)
    {
      s << indent << "  p4[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.p4[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_PLATEPOSITIONRESPONSE_H
